### ISSUE TITLE
Can't get list of accounts

### ISSUE THREAD

**Issue by Marakaya** [autonity/autonity-cli#128]
On piccadilly testnet I cant check my account list when use "aut account list". Error - json.decoder.JSONDecodeError: Extra data: line 1 column 12 (char 11)

Keystore located here - .autonity/keystore
.autrc is:
[aut]
rpc_endpoint=https://rpc1.piccadilly.autonity.org/
keyfile = /root/.autonity/keystore/main.key

**Comment by cmjc** [comment]
I can replicate this issue.

I have tried with the keystore path configured in `.autrc`, and by directly specifying it in the command using the `--keystore` or short form `--s` flags. I get the same error `json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)`.

Interestingly, it works if I explicitly specify the default `keystore`path of `~/.autonity/keystore` explicitly

```
$ aut account list -s ~/.autonity/keystore
0x438CA0aB269d512d636736bDB340bA82e8140C02
0x1e084D9414ECa3Cbb2CE0d4cBF02801F3BA2002d
0x60513247d8C4CB4138A275706F9595BFB9E4d801
0x32725d1d116E07404b76A13419eD057aBb2B0FaC
0x199bEFeAfabED5Ad6EE9b80D0958196ecA54cF95
0x5DDA265Fa715499c81eB0F9bb3e4076a7E98c52c
0xff781909950fc2334B4F733772d5D7B0ff8eBF10
```

**Comment by Marakaya** [comment]
I have this problem even with aut account list -s /root/.autonity/keystore/
json.decoder.JSONDecodeError: Extra data: line 1 column 12 (char 11)

**Comment by aiman** [comment]
This should be fixed in https://github.com/autonity/aut/releases/tag/v0.3.0.dev4, please check.
