### ISSUE TITLE
Warn or fail on incompatible protocol version

### ISSUE THREAD

**Issue by aiman** [autonity/autonity-cli#163]
Running an aut command with an incompatible protocol version may return results that are false or misleading, and in many cases the command will succeed without any error. An example would be a change to the Autonity Contract `config `object.

It may be a good idea to warn or fail due to an error when connecting to an RPC node running a known incompatible or unsupported protocol version.

We may be able to make use of the `web3_clientVersion`, but there may be other indicators of incompatibility.

**Comment by szemate** [comment]
Resolved in version 1.0.0.
